#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

for (sort keys %ENV) {
    print "$_=$ENV{$_}\n";
}

# ABSTRACT: Print environment variables, as seen by a Perl script
# PODNAME:

=head1 SYNOPSIS

 % envperl


=head1 DESCRIPTION

You can compare the output of this script with that of B<printenv> utility or
B<set> (shell internal command).


=head1 SEE ALSO

B<printenv> Unix utility

B<set> (shell internal command)

C<%ENV> variable in L<perlvar>
